In [8]:
import pandas as pd
import numpy as np
from typing import List

In [9]:
new_data = pd.read_csv("reworked_dataset (prot 1).csv", index_col=0)

In [10]:
new_data

,Country code,Country,Region,Subregion,Population 2017,Estimate of firearms in civilian possession,Estimate of Computation civilian firearms method per 100 persons,Method of computation,Registered firearms,Unregistered firearms
0,AFG,Afghanistan,Asia,Southern Asia,34169000.0,4270000,12.5,2.0,NaN,NaN
1,ALB,Albania,Europe,Southern Europe,2911000.0,350000,12.0,2.0,65747.0,284253.0
2,DZA,Algeria,Africa,Northern Africa,41064000.0,877000,2.1,2.0,200000.0,677000.0
3,ASM,American Samoa,Oceania,Polynesia,56000.0,400,0.7,2.0,250.0,150.0
4,AND,Andorra,Europe,Southern Europe,69000.0,10000,14.1,3.0,7599.0,2401.0
...,...,...,...,...,...,...,...,...,...,...
225,VGB,Virgin Islands (U.K.),Americas,Caribbean,31000.0,300,0.8,2.0,48.0,252.0
226,VIR,Virgin Islands (U.S.),Americas,Caribbean,107000.0,18000,16.6,2.0,NaN,NaN
227,YEM,Yemen,Asia,Western Asia,28120000.0,14859000,52.8,2.0,NaN,NaN
228,ZMB,Zambia,Africa,Eastern Africa,17238000.0,158000,0.9,2.0,86642.0,71358.0
229,ZWE,Zimbabwe,Africa,Eastern Africa,16338000.0,455000,2.8,2.0,190685.0,264315.0

In [11]:
loose_ends = new_data.isna().any(axis=1)

In [12]:
loose_ends = loose_ends.replace(False, pd.NA).dropna().index

In [13]:
print(list(new_data.iloc[loose_ends]["Country"]))

['Afghanistan', 'Angola', 'Aruba', 'Azerbaijan', 'Bahrain', 'Benin', 'Bermuda', 'Brunei Darussalam', 'Burkina Faso', 'Burundi', 'Cabo Verde (Cape Verde)', 'Cambodia', 'Cameroon', 'Central African Republic', 'Chad', 'China, Macao SAR', 'Christmas Island', 'Comoros', 'Congo, Republic of', 'CuraÃ§ao', 'Djibouti', 'Dominica', 'Equatorial Guinea', 'Eritrea', 'Ethiopia', 'Faroe Islands', 'French Guiana', 'French Polynesia', 'Gabon', 'Gambia', 'Gibraltar', 'Greenland', 'Grenada', 'Guam', 'Guinea', 'Guinea-Bissau', 'Holy See', 'Hong Kong SAR, China', 'Iran, Islamic Republic of', 'Iraq', 'Kiribati', 'Korea, DPR (North)', "Lao People's Democratic Republic", 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 'Liechtenstein', 'Madagascar', 'Maldives', 'Mali', 'Marshall Islands', 'Martinique', 'Mauritania', 'Mauritius', 'Micronesia, Fed. Sts.', 'Monaco', 'Montserrat', 'Morocco', 'Myanmar', 'Nauru', 'Nigeria', 'Northern Mariana Islands', 'Oman', 'Palau', 'Palestinian Territories', 'Puerto Rico', 'Puntland', 'Qatar', 'RÃ©union', 'Rwanda', 'Saint Kitts and Nevis', 'Saint Lucia', 'Saint Martin (France)', 'San Marino', 'SÃ£o TomÃ© and Principe', 'Saudi Arabia', 'Seychelles', 'Sierra Leone', 'Sint Maarten (Netherlands)', 'Solomon Islands', 'Somalia (South Central)', 'Somaliland', 'South Sudan', 'Syrian Arab Republic', 'Timor-Leste (East Timor)', 'Tonga', 'Turkmenistan', 'United Arab Emirates', 'Uzbekistan', 'Venezuela, Bolivarian Republic of', 'Vietnam', 'Virgin Islands (U.S.)', 'Yemen']